name: Zig Build and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get zig version
              id: zigversion
              run: echo "version=$(cat .zigversion)" >> $GITHUB_OUTPUT
            - uses: mlugg/setup-zig@v2
              with:
                version: ${{ steps.zigversion.outputs.version }}
            - run: zig build test --summary all
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get zig version
              id: zigversion
              run: echo "version=$(cat .zigversion)" >> $GITHUB_OUTPUT
            - uses: mlugg/setup-zig@v2
              with:
                version: ${{ steps.zigversion.outputs.version }}
            - run: zig fmt --check src/*.zig